### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Adamantish** [FarhadG/init#5]
Got it in my bookmark bar. Clicked while on a repo. 
Nothing happens. Here's what shows up in the console:

```
VM384:1 Uncaught TypeError: Cannot read property 'textContent' of undefined(anonymous function) @ VM384:1(anonymous function)
```

**Comment by FarhadG** [comment]
Thanks for the issue, @Adamantish. I believe you may have clicked the link on a page that wasn't the main page of the repo.

The bookmarklet needs the `number of commits` in order to go back in time. So it will work on any page that has the header below, which includes the `number of commits`.

![screen shot 2016-09-09 at 1 00 47 pm](https://cloud.githubusercontent.com/assets/1647596/18401076/8c6d7e0a-768d-11e6-98a7-7e87ec30dadd.png)

I could modify the functionality where it works on every page by making an extra requests and going to the repo's main page, but I wanted to keep the bookmarklet code as lean as possible.

Let me know if you continue having an issue, please reopen this issue.
